# Generated by Django 4.1.3 on 2022-11-24 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 10, 4, 10, 525298))),
                ('title', models.CharField(max_length=100)),
                ('select', models.CharField(max_length=100)),
                ('myfiles', models.FileField(upload_to='MyNotes')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 10, 4, 10, 525298)),
        ),
    ]
